// Professional workflow templates for all 17 industries
// Each template defines a complete conversation flow

import type { WorkflowNode, WorkflowEdge } from './workflow-engine'

interface IndustryWorkflow {
  name: string
  description: string
  trigger: string
  industry: string
  nodes: WorkflowNode[]
  edges: WorkflowEdge[]
}

export const ALL_INDUSTRY_WORKFLOWS: IndustryWorkflow[] = [
  // ─── Dentistry ─────────────────────────────────────────────────────────────
  {
    name: 'Dental Office Receptionist',
    description: 'Complete dental office call flow: scheduling, emergencies, insurance questions, and new patient intake',
    trigger: 'inbound_call',
    industry: 'dentistry',
    nodes: [
      { id: 't', type: 'trigger', label: 'Inbound Call', config: { trigger: 'inbound_call' }, position: { x: 250, y: 0 } },
      { id: 'greet', type: 'play_message', label: 'Welcome', config: { message: 'Thank you for calling! I\'m the office AI assistant. How can I help you today?' }, position: { x: 250, y: 100 } },
      { id: 'lookup', type: 'lookup_contact', label: 'Patient Lookup', config: { lookupBy: 'phone' }, position: { x: 250, y: 180 } },
      { id: 'intent', type: 'ai_response', label: 'Detect Intent', config: { prompt: 'Determine the caller\'s intent: appointment, emergency, insurance_question, new_patient, cancel, or other. Set caller_intent.', setVariable: 'caller_intent' }, position: { x: 250, y: 260 } },
      { id: 'branch', type: 'condition', label: 'Route by Intent', config: { variable: 'caller_intent' }, position: { x: 250, y: 340 } },
      { id: 'emergency', type: 'escalate', label: 'Emergency', config: { message: 'I understand this is urgent. Let me get you to our team immediately. Please stay on the line.', priority: 'urgent' }, position: { x: 0, y: 440 } },
      { id: 'new_patient', type: 'collect_info', label: 'New Patient Intake', config: { fields: ['full_name', 'date_of_birth', 'insurance_provider', 'insurance_id', 'preferred_date'], prompt: 'Welcome! I\'d love to get you set up. Can I get your full name, date of birth, and insurance information? When would you like to come in for your first visit?' }, position: { x: 150, y: 440 } },
      { id: 'schedule', type: 'collect_info', label: 'Schedule Appointment', config: { fields: ['caller_name', 'appointment_type', 'preferred_date', 'preferred_time'], prompt: 'I\'d be happy to schedule that for you. What type of appointment do you need — cleaning, checkup, or something else? What date and time work best?' }, position: { x: 350, y: 440 } },
      { id: 'insurance_q', type: 'ai_response', label: 'Insurance Help', config: { prompt: 'Help the caller with insurance questions. We accept most major dental insurance plans including Delta Dental, Cigna, MetLife, Aetna, and Guardian. For specific coverage questions, offer to verify their benefits.' }, position: { x: 550, y: 440 } },
      { id: 'cancel', type: 'ai_response', label: 'Cancel/Reschedule', config: { prompt: 'Help the caller cancel or reschedule their appointment. Ask for their name to look up the appointment, then offer alternative dates.' }, position: { x: 700, y: 440 } },
      { id: 'confirm', type: 'ai_response', label: 'Confirm Details', config: { prompt: 'Summarize all collected information and ask the caller to confirm. Be friendly and thorough.' }, position: { x: 250, y: 560 } },
      { id: 'book', type: 'book_appointment', label: 'Book', config: { type: '{{appointment_type}}', notes: 'Insurance: {{insurance_provider}}' }, position: { x: 250, y: 640 } },
      { id: 'contact', type: 'create_contact', label: 'Save Patient', config: { source: 'inbound_call', tags: ['dental-patient'] }, position: { x: 250, y: 720 } },
      { id: 'sms', type: 'send_sms', label: 'Confirmation SMS', config: { message: 'Hi {{caller_name}}! Your {{appointment_type}} at our dental office is confirmed for {{preferred_date}} at {{preferred_time}}. Please arrive 15 min early. Reply C to confirm.' }, position: { x: 250, y: 800 } },
      { id: 'end', type: 'end_call', label: 'Goodbye', config: { message: 'Thank you for calling! We look forward to seeing you. Have a wonderful day!' }, position: { x: 250, y: 880 } },
    ],
    edges: [
      { id: 'e1', source: 't', target: 'greet' },
      { id: 'e2', source: 'greet', target: 'lookup' },
      { id: 'e3', source: 'lookup', target: 'intent' },
      { id: 'e4', source: 'intent', target: 'branch' },
      { id: 'e5', source: 'branch', target: 'emergency', condition: 'caller_intent = emergency', label: 'Emergency' },
      { id: 'e6', source: 'branch', target: 'new_patient', condition: 'caller_intent = new_patient', label: 'New Patient' },
      { id: 'e7', source: 'branch', target: 'schedule', condition: 'caller_intent = appointment', label: 'Appointment' },
      { id: 'e8', source: 'branch', target: 'insurance_q', condition: 'caller_intent = insurance_question', label: 'Insurance' },
      { id: 'e9', source: 'branch', target: 'cancel', condition: 'caller_intent = cancel', label: 'Cancel' },
      { id: 'e10', source: 'branch', target: 'schedule', label: 'Default' },
      { id: 'e11', source: 'new_patient', target: 'confirm' },
      { id: 'e12', source: 'schedule', target: 'confirm' },
      { id: 'e13', source: 'confirm', target: 'book' },
      { id: 'e14', source: 'book', target: 'contact' },
      { id: 'e15', source: 'contact', target: 'sms' },
      { id: 'e16', source: 'sms', target: 'end' },
      { id: 'e17', source: 'insurance_q', target: 'end' },
      { id: 'e18', source: 'cancel', target: 'end' },
      { id: 'e19', source: 'emergency', target: 'end' },
    ],
  },

  // ─── Restaurants ───────────────────────────────────────────────────────────
  {
    name: 'Restaurant Host',
    description: 'Handle reservations, takeout orders, menu inquiries, and catering requests',
    trigger: 'inbound_call',
    industry: 'restaurants',
    nodes: [
      { id: 't', type: 'trigger', label: 'Inbound Call', config: { trigger: 'inbound_call' }, position: { x: 250, y: 0 } },
      { id: 'greet', type: 'play_message', label: 'Welcome', config: { message: 'Thanks for calling! How can I help you today — would you like to make a reservation, place a takeout order, or do you have a question about our menu?' }, position: { x: 250, y: 100 } },
      { id: 'intent', type: 'ai_response', label: 'Detect Intent', config: { prompt: 'Determine intent: reservation, takeout, menu_question, catering, hours, or other. Set caller_intent.', setVariable: 'caller_intent' }, position: { x: 250, y: 200 } },
      { id: 'branch', type: 'condition', label: 'Route', config: { variable: 'caller_intent' }, position: { x: 250, y: 300 } },
      { id: 'reservation', type: 'collect_info', label: 'Reservation', config: { fields: ['guest_name', 'party_size', 'date', 'time', 'special_requests'], prompt: 'Wonderful! I\'d be happy to book a table. How many in your party? What date and time? Any dietary restrictions or special occasions?' }, position: { x: 0, y: 400 } },
      { id: 'takeout', type: 'collect_info', label: 'Takeout Order', config: { fields: ['order_items', 'pickup_time', 'guest_name', 'phone'], prompt: 'Great choice ordering to go! What would you like to order? And when would you like to pick it up?' }, position: { x: 200, y: 400 } },
      { id: 'menu', type: 'ai_response', label: 'Menu Help', config: { prompt: 'Help with menu questions. Be knowledgeable about common dishes, allergens, dietary options (vegan, gluten-free, nut-free). Suggest popular items and daily specials.' }, position: { x: 400, y: 400 } },
      { id: 'catering', type: 'collect_info', label: 'Catering', config: { fields: ['event_date', 'guest_count', 'budget', 'contact_name', 'email'], prompt: 'We\'d love to cater your event! How many guests are you expecting? What date? And what\'s your approximate budget per person?' }, position: { x: 600, y: 400 } },
      { id: 'confirm_res', type: 'ai_response', label: 'Confirm', config: { prompt: 'Confirm reservation: {{guest_name}}, party of {{party_size}}, on {{date}} at {{time}}. Special requests: {{special_requests}}.' }, position: { x: 100, y: 520 } },
      { id: 'book', type: 'book_appointment', label: 'Book Table', config: { type: 'Reservation - {{party_size}} guests', notes: '{{special_requests}}' }, position: { x: 100, y: 600 } },
      { id: 'sms', type: 'send_sms', label: 'Confirmation', config: { message: 'Hi {{guest_name}}! Your reservation for {{party_size}} on {{date}} at {{time}} is confirmed. See you soon!' }, position: { x: 250, y: 700 } },
      { id: 'end', type: 'end_call', label: 'Goodbye', config: { message: 'Thank you for calling! We look forward to serving you. Bon appetit!' }, position: { x: 250, y: 800 } },
    ],
    edges: [
      { id: 'e1', source: 't', target: 'greet' },
      { id: 'e2', source: 'greet', target: 'intent' },
      { id: 'e3', source: 'intent', target: 'branch' },
      { id: 'e4', source: 'branch', target: 'reservation', condition: 'caller_intent = reservation', label: 'Reservation' },
      { id: 'e5', source: 'branch', target: 'takeout', condition: 'caller_intent = takeout', label: 'Takeout' },
      { id: 'e6', source: 'branch', target: 'menu', condition: 'caller_intent = menu_question', label: 'Menu' },
      { id: 'e7', source: 'branch', target: 'catering', condition: 'caller_intent = catering', label: 'Catering' },
      { id: 'e8', source: 'branch', target: 'reservation', label: 'Default' },
      { id: 'e9', source: 'reservation', target: 'confirm_res' },
      { id: 'e10', source: 'confirm_res', target: 'book' },
      { id: 'e11', source: 'book', target: 'sms' },
      { id: 'e12', source: 'takeout', target: 'sms' },
      { id: 'e13', source: 'catering', target: 'sms' },
      { id: 'e14', source: 'menu', target: 'end' },
      { id: 'e15', source: 'sms', target: 'end' },
    ],
  },

  // ─── Health Clinics ────────────────────────────────────────────────────────
  {
    name: 'Medical Clinic Receptionist',
    description: 'Patient scheduling, urgent triage, prescription refills, and insurance verification',
    trigger: 'inbound_call',
    industry: 'health clinics',
    nodes: [
      { id: 't', type: 'trigger', label: 'Inbound Call', config: {}, position: { x: 250, y: 0 } },
      { id: 'greet', type: 'play_message', label: 'Welcome', config: { message: 'Thank you for calling. I\'m the clinic\'s AI assistant. How may I help you today?' }, position: { x: 250, y: 80 } },
      { id: 'intent', type: 'ai_response', label: 'Detect Intent', config: { prompt: 'Determine intent: appointment, urgent_care, prescription_refill, test_results, insurance, or other. Set caller_intent.', setVariable: 'caller_intent' }, position: { x: 250, y: 160 } },
      { id: 'branch', type: 'condition', label: 'Route', config: {}, position: { x: 250, y: 240 } },
      { id: 'urgent', type: 'escalate', label: 'Urgent Triage', config: { message: 'I want to make sure you get the right care. Let me connect you with our clinical staff right away.', priority: 'urgent' }, position: { x: 0, y: 340 } },
      { id: 'schedule', type: 'collect_info', label: 'Schedule Visit', config: { fields: ['patient_name', 'visit_reason', 'preferred_date', 'preferred_time', 'insurance_provider'], prompt: 'I\'d be happy to schedule a visit. What\'s the reason for your appointment? When works best for you?' }, position: { x: 200, y: 340 } },
      { id: 'refill', type: 'collect_info', label: 'Rx Refill', config: { fields: ['patient_name', 'medication_name', 'pharmacy_name'], prompt: 'I can help with that refill request. What medication do you need refilled, and which pharmacy should we send it to?' }, position: { x: 450, y: 340 } },
      { id: 'confirm', type: 'ai_response', label: 'Confirm', config: { prompt: 'Summarize what was collected and confirm with the patient. Remind them of any pre-visit instructions.' }, position: { x: 250, y: 460 } },
      { id: 'book', type: 'book_appointment', label: 'Book', config: { type: '{{visit_reason}}' }, position: { x: 250, y: 540 } },
      { id: 'sms', type: 'send_sms', label: 'Confirmation', config: { message: 'Hi {{patient_name}}! Your appointment for {{visit_reason}} is scheduled for {{preferred_date}} at {{preferred_time}}. Please bring your insurance card and arrive 15 min early.' }, position: { x: 250, y: 620 } },
      { id: 'end', type: 'end_call', label: 'Goodbye', config: { message: 'Thank you for calling. Take care and we\'ll see you soon!' }, position: { x: 250, y: 700 } },
    ],
    edges: [
      { id: 'e1', source: 't', target: 'greet' }, { id: 'e2', source: 'greet', target: 'intent' }, { id: 'e3', source: 'intent', target: 'branch' },
      { id: 'e4', source: 'branch', target: 'urgent', condition: 'caller_intent = urgent_care', label: 'Urgent' },
      { id: 'e5', source: 'branch', target: 'schedule', condition: 'caller_intent = appointment', label: 'Appointment' },
      { id: 'e6', source: 'branch', target: 'refill', condition: 'caller_intent = prescription_refill', label: 'Rx Refill' },
      { id: 'e7', source: 'branch', target: 'schedule', label: 'Default' },
      { id: 'e8', source: 'schedule', target: 'confirm' }, { id: 'e9', source: 'confirm', target: 'book' }, { id: 'e10', source: 'book', target: 'sms' },
      { id: 'e11', source: 'sms', target: 'end' }, { id: 'e12', source: 'refill', target: 'end' }, { id: 'e13', source: 'urgent', target: 'end' },
    ],
  },

  // ─── Real Estate ───────────────────────────────────────────────────────────
  {
    name: 'Real Estate Lead Agent',
    description: 'Qualify leads, schedule showings, capture buyer preferences, and route hot leads to agents',
    trigger: 'inbound_call',
    industry: 'real estate',
    nodes: [
      { id: 't', type: 'trigger', label: 'Inbound Call', config: {}, position: { x: 250, y: 0 } },
      { id: 'greet', type: 'play_message', label: 'Welcome', config: { message: 'Hi there! Thanks for calling. Are you looking to buy, sell, or rent a property? I\'d love to help you find exactly what you\'re looking for.' }, position: { x: 250, y: 80 } },
      { id: 'qualify', type: 'collect_info', label: 'Qualify Lead', config: { fields: ['caller_name', 'interest_type', 'property_type', 'budget_range', 'location_preference', 'timeline', 'pre_approved'], prompt: 'Tell me about what you\'re looking for. What type of property? What area? What\'s your budget range? Are you pre-approved for financing?' }, position: { x: 250, y: 180 } },
      { id: 'score', type: 'ai_response', label: 'Score Lead', config: { prompt: 'Score this lead: hot (pre-approved + buying within 30 days), warm (serious but 1-3 months), or cold (just browsing). Set lead_score.', setVariable: 'lead_score' }, position: { x: 250, y: 280 } },
      { id: 'branch', type: 'condition', label: 'Route by Score', config: {}, position: { x: 250, y: 360 } },
      { id: 'hot', type: 'transfer_call', label: 'Transfer to Agent', config: { message: 'Excellent! Based on what you\'ve told me, I\'d love to connect you with one of our top agents who specializes in your area. One moment please.' }, position: { x: 0, y: 460 } },
      { id: 'warm', type: 'collect_info', label: 'Schedule Showing', config: { fields: ['preferred_date', 'preferred_time'], prompt: 'I\'d love to set up a property showing for you. What days and times work best?' }, position: { x: 250, y: 460 } },
      { id: 'cold', type: 'ai_response', label: 'Nurture', config: { prompt: 'Thank them warmly. Offer to send curated listings by email. Ask for their email. Mention we have new listings weekly.' }, position: { x: 500, y: 460 } },
      { id: 'contact', type: 'create_contact', label: 'Save Lead', config: { source: 'inbound_call', tags: ['{{lead_score}}', '{{property_type}}', '{{interest_type}}'] }, position: { x: 250, y: 560 } },
      { id: 'sms', type: 'send_sms', label: 'Follow-Up', config: { message: 'Hi {{caller_name}}! Thanks for your interest in {{property_type}} properties in {{location_preference}}. We\'ll send you matching listings. Reply anytime to chat!' }, position: { x: 250, y: 640 } },
      { id: 'end', type: 'end_call', label: 'Goodbye', config: { message: 'Thank you for calling! We\'ll be in touch with great options for you. Have a wonderful day!' }, position: { x: 250, y: 720 } },
    ],
    edges: [
      { id: 'e1', source: 't', target: 'greet' }, { id: 'e2', source: 'greet', target: 'qualify' }, { id: 'e3', source: 'qualify', target: 'score' }, { id: 'e4', source: 'score', target: 'branch' },
      { id: 'e5', source: 'branch', target: 'hot', condition: 'lead_score = hot', label: 'Hot' },
      { id: 'e6', source: 'branch', target: 'warm', condition: 'lead_score = warm', label: 'Warm' },
      { id: 'e7', source: 'branch', target: 'cold', label: 'Cold' },
      { id: 'e8', source: 'hot', target: 'contact' }, { id: 'e9', source: 'warm', target: 'contact' }, { id: 'e10', source: 'cold', target: 'contact' },
      { id: 'e11', source: 'contact', target: 'sms' }, { id: 'e12', source: 'sms', target: 'end' },
    ],
  },

  // ─── Car Dealerships ───────────────────────────────────────────────────────
  { name: 'Auto Sales Assistant', description: 'Test drive scheduling, inventory inquiries, financing pre-qualification, and trade-in estimates', trigger: 'inbound_call', industry: 'car dealerships',
    nodes: [
      { id: 't', type: 'trigger', label: 'Inbound Call', config: {}, position: { x: 250, y: 0 } },
      { id: 'greet', type: 'play_message', label: 'Welcome', config: { message: 'Thanks for calling! Are you looking for a new or pre-owned vehicle, want to schedule a test drive, or have a question about financing?' }, position: { x: 250, y: 80 } },
      { id: 'intent', type: 'ai_response', label: 'Detect Intent', config: { prompt: 'Determine intent: test_drive, inventory, financing, trade_in, service, or other. Set caller_intent.', setVariable: 'caller_intent' }, position: { x: 250, y: 160 } },
      { id: 'branch', type: 'condition', label: 'Route', config: {}, position: { x: 250, y: 240 } },
      { id: 'test_drive', type: 'collect_info', label: 'Test Drive', config: { fields: ['caller_name', 'vehicle_interest', 'preferred_date', 'preferred_time', 'phone'], prompt: 'Great! What vehicle are you interested in test driving? When would you like to come in?' }, position: { x: 50, y: 340 } },
      { id: 'inventory', type: 'ai_response', label: 'Inventory Help', config: { prompt: 'Help the caller find the right vehicle. Ask about: new/used preference, make/model, budget, must-have features, color preference. Be enthusiastic and knowledgeable.' }, position: { x: 250, y: 340 } },
      { id: 'financing', type: 'collect_info', label: 'Financing', config: { fields: ['caller_name', 'vehicle_interest', 'down_payment', 'credit_range', 'monthly_budget'], prompt: 'I can help you explore financing options! What vehicle are you considering? What\'s your target monthly payment?' }, position: { x: 450, y: 340 } },
      { id: 'contact', type: 'create_contact', label: 'Save Lead', config: { source: 'inbound_call', tags: ['auto-lead', '{{caller_intent}}'] }, position: { x: 250, y: 460 } },
      { id: 'book', type: 'book_appointment', label: 'Book Visit', config: { type: '{{caller_intent}}', notes: 'Vehicle interest: {{vehicle_interest}}' }, position: { x: 250, y: 540 } },
      { id: 'sms', type: 'send_sms', label: 'Confirmation', config: { message: 'Hi {{caller_name}}! Your {{caller_intent}} appointment is confirmed for {{preferred_date}} at {{preferred_time}}. Ask for our sales team when you arrive!' }, position: { x: 250, y: 620 } },
      { id: 'end', type: 'end_call', label: 'Goodbye', config: { message: 'Thank you for calling! We can\'t wait to help you find the perfect vehicle. See you soon!' }, position: { x: 250, y: 700 } },
    ],
    edges: [
      { id: 'e1', source: 't', target: 'greet' }, { id: 'e2', source: 'greet', target: 'intent' }, { id: 'e3', source: 'intent', target: 'branch' },
      { id: 'e4', source: 'branch', target: 'test_drive', condition: 'caller_intent = test_drive', label: 'Test Drive' },
      { id: 'e5', source: 'branch', target: 'inventory', condition: 'caller_intent = inventory', label: 'Inventory' },
      { id: 'e6', source: 'branch', target: 'financing', condition: 'caller_intent = financing', label: 'Financing' },
      { id: 'e7', source: 'branch', target: 'test_drive', label: 'Default' },
      { id: 'e8', source: 'test_drive', target: 'contact' }, { id: 'e9', source: 'financing', target: 'contact' }, { id: 'e10', source: 'inventory', target: 'contact' },
      { id: 'e11', source: 'contact', target: 'book' }, { id: 'e12', source: 'book', target: 'sms' }, { id: 'e13', source: 'sms', target: 'end' },
    ],
  },

  // ─── Hospitality ───────────────────────────────────────────────────────────
  { name: 'Hotel Concierge', description: 'Room reservations, guest services, amenity inquiries, and special requests', trigger: 'inbound_call', industry: 'hospitality',
    nodes: [
      { id: 't', type: 'trigger', label: 'Inbound Call', config: {}, position: { x: 250, y: 0 } },
      { id: 'greet', type: 'play_message', label: 'Welcome', config: { message: 'Thank you for calling! I\'m the hotel\'s AI concierge. Would you like to make a reservation, or are you a current guest needing assistance?' }, position: { x: 250, y: 80 } },
      { id: 'intent', type: 'ai_response', label: 'Detect Intent', config: { prompt: 'Determine intent: reservation, guest_services, amenities, checkout, complaint, or other. Set caller_intent.', setVariable: 'caller_intent' }, position: { x: 250, y: 160 } },
      { id: 'branch', type: 'condition', label: 'Route', config: {}, position: { x: 250, y: 240 } },
      { id: 'reserve', type: 'collect_info', label: 'Reservation', config: { fields: ['guest_name', 'check_in', 'check_out', 'room_type', 'guests', 'special_requests'], prompt: 'I\'d love to book a room for you! What dates are you looking at? Any room preference — standard, suite, or ocean view?' }, position: { x: 100, y: 340 } },
      { id: 'services', type: 'ai_response', label: 'Guest Services', config: { prompt: 'Help the current guest with their needs: room service, housekeeping, transportation, restaurant recommendations, spa bookings, or local attractions. Be warm and attentive.' }, position: { x: 400, y: 340 } },
      { id: 'complaint', type: 'escalate', label: 'Complaint', config: { message: 'I\'m sorry to hear that. Your satisfaction is our top priority. Let me connect you with our guest relations manager immediately.', priority: 'high' }, position: { x: 600, y: 340 } },
      { id: 'book', type: 'book_appointment', label: 'Book Room', config: { type: '{{room_type}} - {{guests}} guests', notes: '{{special_requests}}' }, position: { x: 100, y: 460 } },
      { id: 'sms', type: 'send_sms', label: 'Confirmation', config: { message: 'Hi {{guest_name}}! Your {{room_type}} reservation is confirmed: Check-in {{check_in}}, Check-out {{check_out}}. We look forward to hosting you!' }, position: { x: 250, y: 560 } },
      { id: 'end', type: 'end_call', label: 'Goodbye', config: { message: 'Thank you for choosing us! We look forward to making your stay exceptional.' }, position: { x: 250, y: 640 } },
    ],
    edges: [
      { id: 'e1', source: 't', target: 'greet' }, { id: 'e2', source: 'greet', target: 'intent' }, { id: 'e3', source: 'intent', target: 'branch' },
      { id: 'e4', source: 'branch', target: 'reserve', condition: 'caller_intent = reservation', label: 'Reservation' },
      { id: 'e5', source: 'branch', target: 'services', condition: 'caller_intent = guest_services', label: 'Services' },
      { id: 'e6', source: 'branch', target: 'complaint', condition: 'caller_intent = complaint', label: 'Complaint' },
      { id: 'e7', source: 'branch', target: 'reserve', label: 'Default' },
      { id: 'e8', source: 'reserve', target: 'book' }, { id: 'e9', source: 'book', target: 'sms' }, { id: 'e10', source: 'sms', target: 'end' },
      { id: 'e11', source: 'services', target: 'end' }, { id: 'e12', source: 'complaint', target: 'end' },
    ],
  },

  // ─── Debt Collection ──────────────────────────────────────────────────────
  {
    name: 'Debt Collection Agent',
    description: 'FDCPA-compliant payment negotiation, payment plans, account disputes, and hardship programs',
    trigger: 'inbound_call',
    industry: 'debt collection',
    nodes: [
      { id: 't', type: 'trigger', label: 'Inbound Call', config: { trigger: 'inbound_call' }, position: { x: 250, y: 0 } },
      { id: 'greet', type: 'play_message', label: 'FDCPA Disclosure', config: { message: 'This call is from a debt collection agency. This is an attempt to collect a debt and any information obtained will be used for that purpose. May I have your name and account number to pull up your file?' }, position: { x: 250, y: 80 } },
      { id: 'verify', type: 'collect_info', label: 'Verify Identity', config: { fields: ['debtor_name', 'account_number', 'last_four_ssn', 'date_of_birth'], prompt: 'For security, I need to verify your identity. Can you confirm your full name, account number, and date of birth?' }, position: { x: 250, y: 160 } },
      { id: 'lookup', type: 'lookup_contact', label: 'Account Lookup', config: { lookupBy: 'account_number' }, position: { x: 250, y: 240 } },
      { id: 'intent', type: 'ai_response', label: 'Detect Intent', config: { prompt: 'Determine the caller\'s intent: make_payment, setup_payment_plan, dispute_debt, request_validation, hardship, cease_communication, or balance_inquiry. Set caller_intent.', setVariable: 'caller_intent' }, position: { x: 250, y: 320 } },
      { id: 'branch', type: 'condition', label: 'Route by Intent', config: { variable: 'caller_intent' }, position: { x: 250, y: 400 } },
      { id: 'payment', type: 'collect_info', label: 'Process Payment', config: { fields: ['payment_amount', 'payment_method', 'card_last_four', 'payment_date'], prompt: 'I can help you make a payment. How much would you like to pay today? We accept debit cards, bank transfers, and checks by phone.' }, position: { x: 0, y: 500 } },
      { id: 'plan', type: 'collect_info', label: 'Payment Plan', config: { fields: ['monthly_amount', 'start_date', 'plan_duration', 'payment_method'], prompt: 'Let\'s set up a payment plan that works for your budget. What monthly amount can you commit to? Your current balance is {{balance}}.' }, position: { x: 200, y: 500 } },
      { id: 'dispute', type: 'collect_info', label: 'File Dispute', config: { fields: ['dispute_reason', 'supporting_details'], prompt: 'I understand you\'d like to dispute this debt. Can you tell me the reason for your dispute? We\'ll send a written validation within 30 days as required by law.' }, position: { x: 400, y: 500 } },
      { id: 'hardship', type: 'ai_response', label: 'Hardship Review', config: { prompt: 'The caller is experiencing financial hardship. Ask about their situation compassionately: job loss, medical emergency, disability, or other. Explain our hardship programs: reduced settlements (40-60% of balance), extended plans (up to 36 months), or temporary forbearance. Set hardship_type.' }, position: { x: 600, y: 500 } },
      { id: 'cease', type: 'ai_response', label: 'Cease Request', config: { prompt: 'The caller wants to stop communication. Inform them: "I\'ll note your request. Per FDCPA, we\'ll send written confirmation. Please note this does not eliminate the debt." Log the cease request.' }, position: { x: 750, y: 500 } },
      { id: 'confirm', type: 'ai_response', label: 'Confirm Agreement', config: { prompt: 'Summarize the agreed terms clearly: amount, dates, method. Read back all details and get verbal confirmation. Remind them they\'ll receive written confirmation via mail.' }, position: { x: 250, y: 620 } },
      { id: 'contact', type: 'create_contact', label: 'Update Account', config: { source: 'inbound_call', tags: ['collections', '{{caller_intent}}'] }, position: { x: 250, y: 700 } },
      { id: 'sms', type: 'send_sms', label: 'Payment Confirmation', config: { message: 'Payment confirmation: ${{payment_amount}} scheduled for {{payment_date}} on account {{account_number}}. Ref #{{confirmation_number}}. Questions? Call us back.' }, position: { x: 250, y: 780 } },
      { id: 'end', type: 'end_call', label: 'Goodbye', config: { message: 'Thank you for calling. Your reference number is {{confirmation_number}}. Have a good day.' }, position: { x: 250, y: 860 } },
    ],
    edges: [
      { id: 'e1', source: 't', target: 'greet' }, { id: 'e2', source: 'greet', target: 'verify' },
      { id: 'e3', source: 'verify', target: 'lookup' }, { id: 'e4', source: 'lookup', target: 'intent' },
      { id: 'e5', source: 'intent', target: 'branch' },
      { id: 'e6', source: 'branch', target: 'payment', condition: 'caller_intent = make_payment', label: 'Payment' },
      { id: 'e7', source: 'branch', target: 'plan', condition: 'caller_intent = setup_payment_plan', label: 'Payment Plan' },
      { id: 'e8', source: 'branch', target: 'dispute', condition: 'caller_intent = dispute_debt', label: 'Dispute' },
      { id: 'e9', source: 'branch', target: 'hardship', condition: 'caller_intent = hardship', label: 'Hardship' },
      { id: 'e10', source: 'branch', target: 'cease', condition: 'caller_intent = cease_communication', label: 'Cease' },
      { id: 'e11', source: 'branch', target: 'payment', label: 'Default' },
      { id: 'e12', source: 'payment', target: 'confirm' }, { id: 'e13', source: 'plan', target: 'confirm' },
      { id: 'e14', source: 'hardship', target: 'confirm' },
      { id: 'e15', source: 'confirm', target: 'contact' }, { id: 'e16', source: 'contact', target: 'sms' },
      { id: 'e17', source: 'sms', target: 'end' },
      { id: 'e18', source: 'dispute', target: 'contact' }, { id: 'e19', source: 'cease', target: 'end' },
    ],
  },

  // ─── Insurance ──────────────────────────────────────────────────────────────
  {
    name: 'Insurance Agent',
    description: 'Quote generation, claims filing, policy management, coverage updates, and billing inquiries',
    trigger: 'inbound_call',
    industry: 'insurance',
    nodes: [
      { id: 't', type: 'trigger', label: 'Inbound Call', config: { trigger: 'inbound_call' }, position: { x: 250, y: 0 } },
      { id: 'greet', type: 'play_message', label: 'Welcome', config: { message: 'Thank you for calling! I can help with quotes, claims, policy questions, or billing. What can I assist you with today?' }, position: { x: 250, y: 80 } },
      { id: 'lookup', type: 'lookup_contact', label: 'Policy Lookup', config: { lookupBy: 'phone' }, position: { x: 250, y: 160 } },
      { id: 'intent', type: 'ai_response', label: 'Detect Intent', config: { prompt: 'Determine the caller\'s intent: new_quote, file_claim, policy_question, update_coverage, billing, add_driver, or roadside_assistance. Set caller_intent.', setVariable: 'caller_intent' }, position: { x: 250, y: 240 } },
      { id: 'branch', type: 'condition', label: 'Route by Intent', config: { variable: 'caller_intent' }, position: { x: 250, y: 320 } },
      { id: 'quote', type: 'collect_info', label: 'Generate Quote', config: { fields: ['caller_name', 'coverage_type', 'property_details', 'current_provider', 'desired_start_date'], prompt: 'I\'d love to get you a competitive quote! What type of coverage are you looking for — auto, home, life, or business? Tell me a bit about what you need covered.' }, position: { x: 0, y: 420 } },
      { id: 'claim', type: 'collect_info', label: 'File Claim', config: { fields: ['policy_number', 'incident_date', 'incident_type', 'description', 'police_report_number', 'damage_estimate'], prompt: 'I\'m sorry to hear about your incident. Let me help file your claim. When did this happen? Can you describe what occurred?' }, position: { x: 200, y: 420 } },
      { id: 'policy_q', type: 'ai_response', label: 'Policy Help', config: { prompt: 'Help the caller understand their policy. Explain coverage limits, deductibles, exclusions, and riders in plain language. If they ask about specific scenarios, clarify what is and isn\'t covered. Always recommend they review their declarations page.' }, position: { x: 400, y: 420 } },
      { id: 'update', type: 'collect_info', label: 'Update Coverage', config: { fields: ['policy_number', 'change_type', 'effective_date', 'new_details'], prompt: 'What changes would you like to make to your policy? Adding a vehicle, changing your address, adjusting coverage limits?' }, position: { x: 600, y: 420 } },
      { id: 'billing', type: 'ai_response', label: 'Billing Help', config: { prompt: 'Help with billing: explain charges, payment due dates, autopay setup, payment methods accepted. If they\'re behind, explain grace period (usually 30 days) and reinstatement options.' }, position: { x: 750, y: 420 } },
      { id: 'confirm', type: 'ai_response', label: 'Confirm Details', config: { prompt: 'Summarize all information collected. For claims, provide the claim number. For quotes, explain next steps and timeline. For changes, confirm effective date and premium impact.' }, position: { x: 250, y: 560 } },
      { id: 'contact', type: 'create_contact', label: 'Save Record', config: { source: 'inbound_call', tags: ['insurance', '{{coverage_type}}', '{{caller_intent}}'] }, position: { x: 250, y: 640 } },
      { id: 'sms', type: 'send_sms', label: 'Follow-Up SMS', config: { message: 'Hi {{caller_name}}! Your {{caller_intent}} has been processed. Reference: {{policy_number}}. An agent will follow up within 24 hours if needed. Questions? Call us anytime.' }, position: { x: 250, y: 720 } },
      { id: 'end', type: 'end_call', label: 'Goodbye', config: { message: 'Thank you for calling! We\'re here to protect what matters most. Have a great day!' }, position: { x: 250, y: 800 } },
    ],
    edges: [
      { id: 'e1', source: 't', target: 'greet' }, { id: 'e2', source: 'greet', target: 'lookup' },
      { id: 'e3', source: 'lookup', target: 'intent' }, { id: 'e4', source: 'intent', target: 'branch' },
      { id: 'e5', source: 'branch', target: 'quote', condition: 'caller_intent = new_quote', label: 'New Quote' },
      { id: 'e6', source: 'branch', target: 'claim', condition: 'caller_intent = file_claim', label: 'File Claim' },
      { id: 'e7', source: 'branch', target: 'policy_q', condition: 'caller_intent = policy_question', label: 'Policy Q&A' },
      { id: 'e8', source: 'branch', target: 'update', condition: 'caller_intent = update_coverage', label: 'Update' },
      { id: 'e9', source: 'branch', target: 'billing', condition: 'caller_intent = billing', label: 'Billing' },
      { id: 'e10', source: 'branch', target: 'quote', label: 'Default' },
      { id: 'e11', source: 'quote', target: 'confirm' }, { id: 'e12', source: 'claim', target: 'confirm' },
      { id: 'e13', source: 'update', target: 'confirm' },
      { id: 'e14', source: 'confirm', target: 'contact' }, { id: 'e15', source: 'contact', target: 'sms' },
      { id: 'e16', source: 'sms', target: 'end' },
      { id: 'e17', source: 'policy_q', target: 'end' }, { id: 'e18', source: 'billing', target: 'end' },
    ],
  },

  // ─── Legal ──────────────────────────────────────────────────────────────────
  {
    name: 'Law Firm Intake',
    description: 'Client intake, consultation scheduling, case type routing, conflict checks, and emergency legal matters',
    trigger: 'inbound_call',
    industry: 'legal',
    nodes: [
      { id: 't', type: 'trigger', label: 'Inbound Call', config: { trigger: 'inbound_call' }, position: { x: 250, y: 0 } },
      { id: 'greet', type: 'play_message', label: 'Welcome', config: { message: 'Thank you for calling our law firm. I\'m the intake assistant. Please note this call may be recorded for quality purposes. How can I help you today?' }, position: { x: 250, y: 80 } },
      { id: 'intent', type: 'ai_response', label: 'Detect Intent', config: { prompt: 'Determine the caller\'s intent: new_consultation, case_status, document_request, billing_question, emergency_legal, or existing_client. Set caller_intent.', setVariable: 'caller_intent' }, position: { x: 250, y: 160 } },
      { id: 'branch', type: 'condition', label: 'Route by Intent', config: { variable: 'caller_intent' }, position: { x: 250, y: 240 } },
      { id: 'emergency', type: 'escalate', label: 'Emergency Legal', config: { message: 'I understand this is urgent. Let me connect you with an attorney immediately. Please stay on the line.', priority: 'urgent' }, position: { x: 0, y: 340 } },
      { id: 'intake', type: 'collect_info', label: 'New Client Intake', config: { fields: ['caller_name', 'phone', 'email', 'case_type', 'opposing_party', 'brief_description', 'incident_date', 'referred_by'], prompt: 'I\'d be happy to help you schedule a consultation. First, what type of legal matter is this — personal injury, family law, criminal defense, business, estate planning, or immigration? Can you briefly describe your situation?' }, position: { x: 200, y: 340 } },
      { id: 'conflict', type: 'ai_response', label: 'Conflict Check', config: { prompt: 'Perform a preliminary conflict check. Ask: "Have you or the opposing party ({{opposing_party}}) ever been represented by our firm before?" Log the response. If potential conflict exists, note it for attorney review.' }, position: { x: 200, y: 440 } },
      { id: 'case_status', type: 'collect_info', label: 'Case Status', config: { fields: ['caller_name', 'case_number', 'attorney_name'], prompt: 'I can check on your case. What\'s your case number or the attorney you\'re working with?' }, position: { x: 450, y: 340 } },
      { id: 'billing', type: 'ai_response', label: 'Billing Help', config: { prompt: 'Help with billing questions. Explain: retainer structure, hourly vs flat fee, payment plans available, accepted methods. If they have a specific dispute, note it for the billing department to review.' }, position: { x: 650, y: 340 } },
      { id: 'schedule', type: 'collect_info', label: 'Schedule Consult', config: { fields: ['preferred_date', 'preferred_time', 'consultation_type'], prompt: 'Let me schedule your consultation. Would you prefer in-person, phone, or video? What dates work best for you? Initial consultations are typically 30-60 minutes.' }, position: { x: 250, y: 540 } },
      { id: 'book', type: 'book_appointment', label: 'Book Consultation', config: { type: '{{case_type}} Consultation', notes: 'Opposing party: {{opposing_party}}. Description: {{brief_description}}' }, position: { x: 250, y: 620 } },
      { id: 'contact', type: 'create_contact', label: 'Save Client', config: { source: 'inbound_call', tags: ['legal-intake', '{{case_type}}'] }, position: { x: 250, y: 700 } },
      { id: 'sms', type: 'send_sms', label: 'Confirmation', config: { message: 'Hi {{caller_name}}! Your {{case_type}} consultation is confirmed for {{preferred_date}} at {{preferred_time}}. Please bring: photo ID, relevant documents, and a timeline of events. Reply with questions.' }, position: { x: 250, y: 780 } },
      { id: 'end', type: 'end_call', label: 'Goodbye', config: { message: 'Thank you for calling. We look forward to helping you with your legal matter. Have a good day.' }, position: { x: 250, y: 860 } },
    ],
    edges: [
      { id: 'e1', source: 't', target: 'greet' }, { id: 'e2', source: 'greet', target: 'intent' },
      { id: 'e3', source: 'intent', target: 'branch' },
      { id: 'e4', source: 'branch', target: 'emergency', condition: 'caller_intent = emergency_legal', label: 'Emergency' },
      { id: 'e5', source: 'branch', target: 'intake', condition: 'caller_intent = new_consultation', label: 'New Client' },
      { id: 'e6', source: 'branch', target: 'case_status', condition: 'caller_intent = case_status', label: 'Case Status' },
      { id: 'e7', source: 'branch', target: 'billing', condition: 'caller_intent = billing_question', label: 'Billing' },
      { id: 'e8', source: 'branch', target: 'intake', label: 'Default' },
      { id: 'e9', source: 'intake', target: 'conflict' }, { id: 'e10', source: 'conflict', target: 'schedule' },
      { id: 'e11', source: 'schedule', target: 'book' }, { id: 'e12', source: 'book', target: 'contact' },
      { id: 'e13', source: 'contact', target: 'sms' }, { id: 'e14', source: 'sms', target: 'end' },
      { id: 'e15', source: 'case_status', target: 'end' }, { id: 'e16', source: 'billing', target: 'end' },
      { id: 'e17', source: 'emergency', target: 'end' },
    ],
  },

  // ─── Home Services ──────────────────────────────────────────────────────────
  {
    name: 'Home Services Dispatcher',
    description: 'Service scheduling, emergency dispatch, free estimates, warranty work, and follow-up coordination',
    trigger: 'inbound_call',
    industry: 'home services',
    nodes: [
      { id: 't', type: 'trigger', label: 'Inbound Call', config: { trigger: 'inbound_call' }, position: { x: 250, y: 0 } },
      { id: 'greet', type: 'play_message', label: 'Welcome', config: { message: 'Thanks for calling! We handle plumbing, electrical, HVAC, and general repairs. Is this an emergency, or would you like to schedule a service or get a free estimate?' }, position: { x: 250, y: 80 } },
      { id: 'intent', type: 'ai_response', label: 'Detect Intent', config: { prompt: 'Determine the caller\'s intent: emergency_service, schedule_repair, free_estimate, warranty_claim, follow_up, or complaint. Set caller_intent. If emergency (flooding, gas leak, no heat in winter, electrical fire risk), mark as urgent.', setVariable: 'caller_intent' }, position: { x: 250, y: 160 } },
      { id: 'branch', type: 'condition', label: 'Route by Intent', config: { variable: 'caller_intent' }, position: { x: 250, y: 240 } },
      { id: 'emergency', type: 'escalate', label: 'Emergency Dispatch', config: { message: 'I\'m dispatching an emergency technician right away. They\'ll call you within 15 minutes with an ETA. In the meantime, please turn off the main water/gas valve if safe to do so.', priority: 'urgent' }, position: { x: 0, y: 340 } },
      { id: 'schedule', type: 'collect_info', label: 'Schedule Service', config: { fields: ['caller_name', 'phone', 'address', 'service_type', 'issue_description', 'preferred_date', 'preferred_time', 'access_instructions'], prompt: 'I\'d be happy to schedule that for you. What type of service do you need? Can you describe the issue? What\'s the address, and when works best for you?' }, position: { x: 200, y: 340 } },
      { id: 'estimate', type: 'collect_info', label: 'Free Estimate', config: { fields: ['caller_name', 'phone', 'address', 'project_description', 'project_scope', 'preferred_date'], prompt: 'Our free estimates include a thorough inspection and written quote. What project are you considering? How large is the space? We can usually schedule within 2-3 business days.' }, position: { x: 450, y: 340 } },
      { id: 'warranty', type: 'collect_info', label: 'Warranty Claim', config: { fields: ['caller_name', 'original_service_date', 'technician_name', 'issue_description'], prompt: 'All our work is backed by warranty. When was the original service performed? What issue are you experiencing? I\'ll get a tech back out to you at no charge.' }, position: { x: 650, y: 340 } },
      { id: 'complaint', type: 'escalate', label: 'Complaint', config: { message: 'I\'m sorry about your experience. Let me connect you with our service manager who can make this right immediately.', priority: 'high' }, position: { x: 800, y: 340 } },
      { id: 'confirm', type: 'ai_response', label: 'Confirm Details', config: { prompt: 'Confirm the appointment: service type, address, date, time, and any special instructions. Let them know the tech will call 30 minutes before arrival. Mention our satisfaction guarantee.' }, position: { x: 250, y: 480 } },
      { id: 'book', type: 'book_appointment', label: 'Book Service', config: { type: '{{service_type}}', notes: 'Issue: {{issue_description}}. Access: {{access_instructions}}' }, position: { x: 250, y: 560 } },
      { id: 'contact', type: 'create_contact', label: 'Save Customer', config: { source: 'inbound_call', tags: ['home-services', '{{service_type}}'] }, position: { x: 250, y: 640 } },
      { id: 'sms', type: 'send_sms', label: 'Confirmation SMS', config: { message: 'Hi {{caller_name}}! Your {{service_type}} appointment at {{address}} is confirmed for {{preferred_date}} at {{preferred_time}}. Your tech will call 30 min before arriving. Reply HELP anytime.' }, position: { x: 250, y: 720 } },
      { id: 'end', type: 'end_call', label: 'Goodbye', config: { message: 'Thank you for choosing us! We stand behind every job with our satisfaction guarantee. See you soon!' }, position: { x: 250, y: 800 } },
    ],
    edges: [
      { id: 'e1', source: 't', target: 'greet' }, { id: 'e2', source: 'greet', target: 'intent' },
      { id: 'e3', source: 'intent', target: 'branch' },
      { id: 'e4', source: 'branch', target: 'emergency', condition: 'caller_intent = emergency_service', label: 'Emergency' },
      { id: 'e5', source: 'branch', target: 'schedule', condition: 'caller_intent = schedule_repair', label: 'Schedule' },
      { id: 'e6', source: 'branch', target: 'estimate', condition: 'caller_intent = free_estimate', label: 'Estimate' },
      { id: 'e7', source: 'branch', target: 'warranty', condition: 'caller_intent = warranty_claim', label: 'Warranty' },
      { id: 'e8', source: 'branch', target: 'complaint', condition: 'caller_intent = complaint', label: 'Complaint' },
      { id: 'e9', source: 'branch', target: 'schedule', label: 'Default' },
      { id: 'e10', source: 'schedule', target: 'confirm' }, { id: 'e11', source: 'estimate', target: 'confirm' },
      { id: 'e12', source: 'warranty', target: 'confirm' },
      { id: 'e13', source: 'confirm', target: 'book' }, { id: 'e14', source: 'book', target: 'contact' },
      { id: 'e15', source: 'contact', target: 'sms' }, { id: 'e16', source: 'sms', target: 'end' },
      { id: 'e17', source: 'emergency', target: 'end' }, { id: 'e18', source: 'complaint', target: 'end' },
    ],
  },

  // ─── Pharmacy ───────────────────────────────────────────────────────────────
  {
    name: 'Pharmacy Assistant',
    description: 'Prescription refills, medication counseling, immunization scheduling, insurance verification, and transfers',
    trigger: 'inbound_call',
    industry: 'pharmacy',
    nodes: [
      { id: 't', type: 'trigger', label: 'Inbound Call', config: { trigger: 'inbound_call' }, position: { x: 250, y: 0 } },
      { id: 'greet', type: 'play_message', label: 'Welcome', config: { message: 'Thank you for calling the pharmacy! I can help with prescription refills, medication questions, immunizations, or insurance. How can I help you today?' }, position: { x: 250, y: 80 } },
      { id: 'verify', type: 'collect_info', label: 'Verify Patient', config: { fields: ['patient_name', 'date_of_birth'], prompt: 'For your safety, may I have your full name and date of birth to pull up your profile?' }, position: { x: 250, y: 160 } },
      { id: 'lookup', type: 'lookup_contact', label: 'Patient Lookup', config: { lookupBy: 'name_dob' }, position: { x: 250, y: 240 } },
      { id: 'intent', type: 'ai_response', label: 'Detect Intent', config: { prompt: 'Determine the caller\'s intent: refill, new_prescription, medication_question, immunization, insurance_issue, transfer_rx, or otc_recommendation. Set caller_intent.', setVariable: 'caller_intent' }, position: { x: 250, y: 320 } },
      { id: 'branch', type: 'condition', label: 'Route by Intent', config: { variable: 'caller_intent' }, position: { x: 250, y: 400 } },
      { id: 'refill', type: 'collect_info', label: 'Process Refill', config: { fields: ['rx_number', 'medication_name', 'pickup_time'], prompt: 'I can process that refill. Do you have the Rx number from the bottle, or the medication name? When would you like to pick it up? We have drive-through available too.' }, position: { x: 0, y: 500 } },
      { id: 'med_question', type: 'ai_response', label: 'Medication Counseling', config: { prompt: 'Help with medication questions: side effects, interactions, dosage timing, food interactions, storage. Always recommend speaking with the pharmacist for complex clinical questions. Never diagnose or change prescribed dosages. Common advice: take with food if GI upset, avoid grapefruit with statins, timing for AM vs PM medications.' }, position: { x: 200, y: 500 } },
      { id: 'immunization', type: 'collect_info', label: 'Schedule Vaccine', config: { fields: ['vaccine_type', 'insurance_provider', 'preferred_date', 'preferred_time', 'allergies'], prompt: 'We offer flu, COVID, shingles, pneumonia, Tdap, and hepatitis vaccines. Which vaccine are you interested in? Do you have any allergies we should know about?' }, position: { x: 400, y: 500 } },
      { id: 'insurance', type: 'ai_response', label: 'Insurance Help', config: { prompt: 'Help with insurance issues: prior authorization status, formulary alternatives, copay assistance programs, discount cards (GoodRx, manufacturer coupons). If medication is too expensive, suggest asking the pharmacist about generic alternatives or patient assistance programs.' }, position: { x: 600, y: 500 } },
      { id: 'transfer', type: 'collect_info', label: 'Transfer Rx', config: { fields: ['medication_name', 'current_pharmacy', 'current_pharmacy_phone'], prompt: 'I can transfer your prescription to our pharmacy. What medication is it? Which pharmacy currently has it? We\'ll handle the transfer — usually ready within 2-4 hours.' }, position: { x: 750, y: 500 } },
      { id: 'confirm', type: 'ai_response', label: 'Confirm', config: { prompt: 'Summarize: medication name, pickup time, any special instructions. Remind about checking for drug interactions if they\'re on multiple medications.' }, position: { x: 250, y: 620 } },
      { id: 'contact', type: 'create_contact', label: 'Update Record', config: { source: 'inbound_call', tags: ['pharmacy-patient'] }, position: { x: 250, y: 700 } },
      { id: 'sms', type: 'send_sms', label: 'Ready Notification', config: { message: 'Hi {{patient_name}}! Your {{medication_name}} will be ready for pickup by {{pickup_time}}. Drive-through and curbside available. Questions about your meds? Our pharmacist is here to help.' }, position: { x: 250, y: 780 } },
      { id: 'end', type: 'end_call', label: 'Goodbye', config: { message: 'Thank you for calling! We\'ll have that ready for you. Stay healthy!' }, position: { x: 250, y: 860 } },
    ],
    edges: [
      { id: 'e1', source: 't', target: 'greet' }, { id: 'e2', source: 'greet', target: 'verify' },
      { id: 'e3', source: 'verify', target: 'lookup' }, { id: 'e4', source: 'lookup', target: 'intent' },
      { id: 'e5', source: 'intent', target: 'branch' },
      { id: 'e6', source: 'branch', target: 'refill', condition: 'caller_intent = refill', label: 'Refill' },
      { id: 'e7', source: 'branch', target: 'med_question', condition: 'caller_intent = medication_question', label: 'Med Question' },
      { id: 'e8', source: 'branch', target: 'immunization', condition: 'caller_intent = immunization', label: 'Vaccine' },
      { id: 'e9', source: 'branch', target: 'insurance', condition: 'caller_intent = insurance_issue', label: 'Insurance' },
      { id: 'e10', source: 'branch', target: 'transfer', condition: 'caller_intent = transfer_rx', label: 'Transfer' },
      { id: 'e11', source: 'branch', target: 'refill', label: 'Default' },
      { id: 'e12', source: 'refill', target: 'confirm' }, { id: 'e13', source: 'immunization', target: 'confirm' },
      { id: 'e14', source: 'transfer', target: 'confirm' },
      { id: 'e15', source: 'confirm', target: 'contact' }, { id: 'e16', source: 'contact', target: 'sms' },
      { id: 'e17', source: 'sms', target: 'end' },
      { id: 'e18', source: 'med_question', target: 'end' }, { id: 'e19', source: 'insurance', target: 'end' },
    ],
  },

  // ─── Fitness ────────────────────────────────────────────────────────────────
  {
    name: 'Fitness Center Concierge',
    description: 'Membership sign-ups, class bookings, personal training sessions, facility tours, and account management',
    trigger: 'inbound_call',
    industry: 'fitness',
    nodes: [
      { id: 't', type: 'trigger', label: 'Inbound Call', config: { trigger: 'inbound_call' }, position: { x: 250, y: 0 } },
      { id: 'greet', type: 'play_message', label: 'Welcome', config: { message: 'Hey! Thanks for calling! Are you interested in joining, want to book a class, schedule personal training, or need help with your account?' }, position: { x: 250, y: 80 } },
      { id: 'intent', type: 'ai_response', label: 'Detect Intent', config: { prompt: 'Determine the caller\'s intent: new_membership, class_booking, personal_training, facility_tour, freeze_cancel, group_rates, or hours_info. Set caller_intent.', setVariable: 'caller_intent' }, position: { x: 250, y: 160 } },
      { id: 'branch', type: 'condition', label: 'Route', config: { variable: 'caller_intent' }, position: { x: 250, y: 240 } },
      { id: 'membership', type: 'collect_info', label: 'New Membership', config: { fields: ['caller_name', 'phone', 'email', 'fitness_goals', 'membership_type', 'start_date'], prompt: 'Awesome that you\'re interested! What are your fitness goals? We have Basic ($29/mo — gym access), Premium ($49/mo — classes included), and Elite ($79/mo — personal training sessions included). Which sounds right for you?' }, position: { x: 0, y: 340 } },
      { id: 'class', type: 'collect_info', label: 'Book Class', config: { fields: ['member_name', 'class_type', 'preferred_date', 'preferred_time'], prompt: 'We have yoga, spin, HIIT, Pilates, boxing, and Zumba. What sounds good? Most classes are 45-60 minutes. What day and time work best?' }, position: { x: 200, y: 340 } },
      { id: 'training', type: 'collect_info', label: 'Personal Training', config: { fields: ['caller_name', 'fitness_goals', 'experience_level', 'preferred_schedule', 'budget'], prompt: 'Personal training is the fastest way to hit your goals! Are you beginner, intermediate, or advanced? What are you focused on — weight loss, muscle building, flexibility, or sport-specific? How many sessions per week are you thinking?' }, position: { x: 400, y: 340 } },
      { id: 'tour', type: 'collect_info', label: 'Schedule Tour', config: { fields: ['caller_name', 'phone', 'preferred_date', 'preferred_time'], prompt: 'We\'d love to show you around! Tours take about 20 minutes and include a free day pass. When would you like to come in?' }, position: { x: 600, y: 340 } },
      { id: 'freeze', type: 'ai_response', label: 'Freeze/Cancel', config: { prompt: 'Help with account changes. Freeze options: medical freeze (free with doctor\'s note), travel freeze ($10/mo, up to 3 months). Cancellation: 30-day notice required, offer to discuss what would make them stay — maybe a plan downgrade or freeze instead.' }, position: { x: 750, y: 340 } },
      { id: 'confirm', type: 'ai_response', label: 'Confirm', config: { prompt: 'Confirm all details. For memberships, explain: no enrollment fee this month, 7-day money-back guarantee, first session with a trainer included free. Build excitement about their fitness journey!' }, position: { x: 250, y: 480 } },
      { id: 'book', type: 'book_appointment', label: 'Book', config: { type: '{{caller_intent}}', notes: 'Goals: {{fitness_goals}}' }, position: { x: 250, y: 560 } },
      { id: 'contact', type: 'create_contact', label: 'Save Member', config: { source: 'inbound_call', tags: ['fitness', '{{caller_intent}}'] }, position: { x: 250, y: 640 } },
      { id: 'sms', type: 'send_sms', label: 'Welcome SMS', config: { message: 'Hey {{caller_name}}! You\'re all set for {{preferred_date}} at {{preferred_time}}. Bring water, a towel, and your best energy! See you soon!' }, position: { x: 250, y: 720 } },
      { id: 'end', type: 'end_call', label: 'Goodbye', config: { message: 'Thanks for calling! Can\'t wait to see you crush your goals. Let\'s go!' }, position: { x: 250, y: 800 } },
    ],
    edges: [
      { id: 'e1', source: 't', target: 'greet' }, { id: 'e2', source: 'greet', target: 'intent' },
      { id: 'e3', source: 'intent', target: 'branch' },
      { id: 'e4', source: 'branch', target: 'membership', condition: 'caller_intent = new_membership', label: 'Membership' },
      { id: 'e5', source: 'branch', target: 'class', condition: 'caller_intent = class_booking', label: 'Book Class' },
      { id: 'e6', source: 'branch', target: 'training', condition: 'caller_intent = personal_training', label: 'Training' },
      { id: 'e7', source: 'branch', target: 'tour', condition: 'caller_intent = facility_tour', label: 'Tour' },
      { id: 'e8', source: 'branch', target: 'freeze', condition: 'caller_intent = freeze_cancel', label: 'Freeze/Cancel' },
      { id: 'e9', source: 'branch', target: 'tour', label: 'Default' },
      { id: 'e10', source: 'membership', target: 'confirm' }, { id: 'e11', source: 'class', target: 'confirm' },
      { id: 'e12', source: 'training', target: 'confirm' }, { id: 'e13', source: 'tour', target: 'confirm' },
      { id: 'e14', source: 'confirm', target: 'book' }, { id: 'e15', source: 'book', target: 'contact' },
      { id: 'e16', source: 'contact', target: 'sms' }, { id: 'e17', source: 'sms', target: 'end' },
      { id: 'e18', source: 'freeze', target: 'end' },
    ],
  },

  // ─── Education ──────────────────────────────────────────────────────────────
  {
    name: 'Education Enrollment Advisor',
    description: 'Enrollment inquiries, campus tours, financial aid guidance, program information, and transcript requests',
    trigger: 'inbound_call',
    industry: 'education',
    nodes: [
      { id: 't', type: 'trigger', label: 'Inbound Call', config: { trigger: 'inbound_call' }, position: { x: 250, y: 0 } },
      { id: 'greet', type: 'play_message', label: 'Welcome', config: { message: 'Thank you for calling! I\'m here to help with admissions, campus tours, financial aid, program information, or student services. What can I help you with?' }, position: { x: 250, y: 80 } },
      { id: 'intent', type: 'ai_response', label: 'Detect Intent', config: { prompt: 'Determine the caller\'s intent: enrollment, campus_tour, financial_aid, program_info, transcript_request, transfer_credits, or current_student. Set caller_intent.', setVariable: 'caller_intent' }, position: { x: 250, y: 160 } },
      { id: 'branch', type: 'condition', label: 'Route', config: { variable: 'caller_intent' }, position: { x: 250, y: 240 } },
      { id: 'enroll', type: 'collect_info', label: 'Enrollment Inquiry', config: { fields: ['student_name', 'email', 'phone', 'program_interest', 'education_level', 'start_term', 'gpa_range'], prompt: 'Exciting that you\'re considering us! What program are you interested in? What\'s your highest level of education completed? When would you like to start — fall, spring, or summer term?' }, position: { x: 0, y: 340 } },
      { id: 'tour', type: 'collect_info', label: 'Campus Tour', config: { fields: ['visitor_name', 'guests_count', 'program_interest', 'preferred_date', 'preferred_time'], prompt: 'We\'d love to show you around! Campus tours are about 90 minutes and include meeting with faculty. How many will be visiting? What program are you interested in seeing? We have tours Tuesday through Saturday.' }, position: { x: 200, y: 340 } },
      { id: 'finaid', type: 'ai_response', label: 'Financial Aid', config: { prompt: 'Help with financial aid questions. Cover: FAFSA deadline and process, merit scholarships (GPA 3.5+ for academic), need-based grants, work-study programs, payment plans (interest-free monthly). Mention: "Have you filed your FAFSA? Our school code is on our website." For specific award amounts, offer to connect with a financial aid counselor.' }, position: { x: 400, y: 340 } },
      { id: 'program', type: 'ai_response', label: 'Program Info', config: { prompt: 'Provide program information: curriculum highlights, career outcomes, faculty expertise, class sizes, internship opportunities, accreditation status. Ask about their career goals to recommend the best-fit program. Mention upcoming info sessions if available.' }, position: { x: 600, y: 340 } },
      { id: 'transcript', type: 'collect_info', label: 'Transcript Request', config: { fields: ['student_name', 'student_id', 'graduation_year', 'destination_address', 'copies_needed'], prompt: 'I can help with your transcript request. Official transcripts are $10 each, typically processed in 3-5 business days. Rush delivery is available for $25. Where should we send them?' }, position: { x: 750, y: 340 } },
      { id: 'qualify', type: 'ai_response', label: 'Assess Fit', config: { prompt: 'Based on their GPA, education level, and program interest, give an encouraging but honest assessment. Mention: application deadline, required documents (transcripts, essays, test scores), and any upcoming open house events.' }, position: { x: 100, y: 480 } },
      { id: 'book', type: 'book_appointment', label: 'Schedule Visit', config: { type: '{{caller_intent}} - {{program_interest}}', notes: 'Education: {{education_level}}, GPA: {{gpa_range}}' }, position: { x: 250, y: 560 } },
      { id: 'contact', type: 'create_contact', label: 'Save Prospect', config: { source: 'inbound_call', tags: ['education', '{{program_interest}}', '{{start_term}}'] }, position: { x: 250, y: 640 } },
      { id: 'sms', type: 'send_sms', label: 'Follow-Up', config: { message: 'Hi {{student_name}}! Thanks for your interest in {{program_interest}}. Your visit is scheduled for {{preferred_date}}. Check your email for a digital brochure and next steps. We\'re excited to meet you!' }, position: { x: 250, y: 720 } },
      { id: 'end', type: 'end_call', label: 'Goodbye', config: { message: 'Thank you for your interest! We\'re excited about your future here. Don\'t hesitate to call back with any questions!' }, position: { x: 250, y: 800 } },
    ],
    edges: [
      { id: 'e1', source: 't', target: 'greet' }, { id: 'e2', source: 'greet', target: 'intent' },
      { id: 'e3', source: 'intent', target: 'branch' },
      { id: 'e4', source: 'branch', target: 'enroll', condition: 'caller_intent = enrollment', label: 'Enroll' },
      { id: 'e5', source: 'branch', target: 'tour', condition: 'caller_intent = campus_tour', label: 'Tour' },
      { id: 'e6', source: 'branch', target: 'finaid', condition: 'caller_intent = financial_aid', label: 'Financial Aid' },
      { id: 'e7', source: 'branch', target: 'program', condition: 'caller_intent = program_info', label: 'Programs' },
      { id: 'e8', source: 'branch', target: 'transcript', condition: 'caller_intent = transcript_request', label: 'Transcripts' },
      { id: 'e9', source: 'branch', target: 'enroll', label: 'Default' },
      { id: 'e10', source: 'enroll', target: 'qualify' }, { id: 'e11', source: 'qualify', target: 'book' },
      { id: 'e12', source: 'tour', target: 'book' },
      { id: 'e13', source: 'book', target: 'contact' }, { id: 'e14', source: 'contact', target: 'sms' },
      { id: 'e15', source: 'sms', target: 'end' },
      { id: 'e16', source: 'finaid', target: 'end' }, { id: 'e17', source: 'program', target: 'end' },
      { id: 'e18', source: 'transcript', target: 'end' },
    ],
  },

  // ─── Pet Care ───────────────────────────────────────────────────────────────
  {
    name: 'Veterinary Receptionist',
    description: 'Pet appointments, emergency triage, grooming & boarding reservations, medication refills, and records requests',
    trigger: 'inbound_call',
    industry: 'pet care',
    nodes: [
      { id: 't', type: 'trigger', label: 'Inbound Call', config: { trigger: 'inbound_call' }, position: { x: 250, y: 0 } },
      { id: 'greet', type: 'play_message', label: 'Welcome', config: { message: 'Thank you for calling! We\'re here for your fur babies. Is this for a vet appointment, an emergency, grooming, boarding, or medication needs?' }, position: { x: 250, y: 80 } },
      { id: 'intent', type: 'ai_response', label: 'Detect Intent', config: { prompt: 'Determine the caller\'s intent: wellness_visit, sick_pet, emergency, grooming, boarding, medication_refill, vaccination, or records_request. If the pet is in immediate distress (difficulty breathing, seizure, poisoning, hit by car), mark as emergency. Set caller_intent.', setVariable: 'caller_intent' }, position: { x: 250, y: 160 } },
      { id: 'branch', type: 'condition', label: 'Route', config: { variable: 'caller_intent' }, position: { x: 250, y: 240 } },
      { id: 'emergency', type: 'escalate', label: 'Pet Emergency', config: { message: 'I understand this is an emergency. Please bring your pet in immediately — we\'ll have a vet tech ready at the door. If you\'re more than 20 minutes away, I can also refer you to the nearest emergency animal hospital.', priority: 'urgent' }, position: { x: 0, y: 340 } },
      { id: 'wellness', type: 'collect_info', label: 'Wellness Visit', config: { fields: ['owner_name', 'pet_name', 'pet_type', 'pet_breed', 'pet_age', 'visit_reason', 'preferred_date', 'preferred_time'], prompt: 'I\'d love to get your pet scheduled! What\'s your pet\'s name and what kind of animal? Is this for a routine checkup, vaccinations, or a specific concern? When works best for you?' }, position: { x: 200, y: 340 } },
      { id: 'sick', type: 'collect_info', label: 'Sick Pet Visit', config: { fields: ['owner_name', 'pet_name', 'pet_type', 'symptoms', 'symptom_duration', 'eating_drinking'], prompt: 'I\'m sorry to hear your pet isn\'t feeling well. What symptoms are you seeing? How long has this been going on? Is your pet still eating and drinking normally? We\'ll try to get you in as soon as possible.' }, position: { x: 400, y: 340 } },
      { id: 'grooming', type: 'collect_info', label: 'Grooming', config: { fields: ['owner_name', 'pet_name', 'pet_breed', 'services_needed', 'preferred_date', 'special_instructions'], prompt: 'Our grooming services include bath & brush, full groom, nail trim, ear cleaning, and de-shedding treatments. What does your pet need? Any special requests — sensitive skin shampoo, specific cut style?' }, position: { x: 600, y: 340 } },
      { id: 'boarding', type: 'collect_info', label: 'Boarding', config: { fields: ['owner_name', 'pet_name', 'pet_type', 'check_in', 'check_out', 'special_diet', 'medications'], prompt: 'We\'d love to take care of your pet while you\'re away! What dates do you need? Any special dietary needs or medications? We offer standard kennels, luxury suites, and outdoor play packages.' }, position: { x: 750, y: 340 } },
      { id: 'medication', type: 'collect_info', label: 'Medication Refill', config: { fields: ['owner_name', 'pet_name', 'medication_name', 'pickup_time'], prompt: 'I can process that refill. Which medication does your pet need? Most refills are ready within 2-4 hours. We also offer home delivery for prescription food and medications.' }, position: { x: 200, y: 480 } },
      { id: 'confirm', type: 'ai_response', label: 'Confirm Details', config: { prompt: 'Confirm the appointment details. For wellness visits, remind about: bring vaccination records, fast if bloodwork is needed. For grooming, confirm drop-off and pickup times. For boarding, confirm vaccination requirements (rabies, distemper, bordetella).' }, position: { x: 250, y: 580 } },
      { id: 'book', type: 'book_appointment', label: 'Book', config: { type: '{{caller_intent}} - {{pet_name}} ({{pet_type}})', notes: 'Reason: {{visit_reason}}{{symptoms}}. Owner: {{owner_name}}' }, position: { x: 250, y: 660 } },
      { id: 'contact', type: 'create_contact', label: 'Save Pet Parent', config: { source: 'inbound_call', tags: ['pet-care', '{{pet_type}}', '{{caller_intent}}'] }, position: { x: 250, y: 740 } },
      { id: 'sms', type: 'send_sms', label: 'Confirmation', config: { message: 'Hi {{owner_name}}! {{pet_name}}\'s {{caller_intent}} appointment is confirmed for {{preferred_date}} at {{preferred_time}}. Please bring vaccination records. We can\'t wait to see {{pet_name}}!' }, position: { x: 250, y: 820 } },
      { id: 'end', type: 'end_call', label: 'Goodbye', config: { message: 'Thank you for calling! Give {{pet_name}} a treat from us. See you soon!' }, position: { x: 250, y: 900 } },
    ],
    edges: [
      { id: 'e1', source: 't', target: 'greet' }, { id: 'e2', source: 'greet', target: 'intent' },
      { id: 'e3', source: 'intent', target: 'branch' },
      { id: 'e4', source: 'branch', target: 'emergency', condition: 'caller_intent = emergency', label: 'Emergency' },
      { id: 'e5', source: 'branch', target: 'wellness', condition: 'caller_intent = wellness_visit', label: 'Wellness' },
      { id: 'e6', source: 'branch', target: 'sick', condition: 'caller_intent = sick_pet', label: 'Sick Pet' },
      { id: 'e7', source: 'branch', target: 'grooming', condition: 'caller_intent = grooming', label: 'Grooming' },
      { id: 'e8', source: 'branch', target: 'boarding', condition: 'caller_intent = boarding', label: 'Boarding' },
      { id: 'e9', source: 'branch', target: 'medication', condition: 'caller_intent = medication_refill', label: 'Medication' },
      { id: 'e10', source: 'branch', target: 'wellness', label: 'Default' },
      { id: 'e11', source: 'wellness', target: 'confirm' }, { id: 'e12', source: 'sick', target: 'confirm' },
      { id: 'e13', source: 'grooming', target: 'confirm' }, { id: 'e14', source: 'boarding', target: 'confirm' },
      { id: 'e15', source: 'medication', target: 'confirm' },
      { id: 'e16', source: 'confirm', target: 'book' }, { id: 'e17', source: 'book', target: 'contact' },
      { id: 'e18', source: 'contact', target: 'sms' }, { id: 'e19', source: 'sms', target: 'end' },
      { id: 'e20', source: 'emergency', target: 'end' },
    ],
  },

  // ─── Accounting & Tax ───────────────────────────────────────────────────────
  {
    name: 'Accounting Firm Assistant',
    description: 'Tax preparation scheduling, document collection guidance, consultation booking, deadline reminders, and billing',
    trigger: 'inbound_call',
    industry: 'accounting',
    nodes: [
      { id: 't', type: 'trigger', label: 'Inbound Call', config: { trigger: 'inbound_call' }, position: { x: 250, y: 0 } },
      { id: 'greet', type: 'play_message', label: 'Welcome', config: { message: 'Thank you for calling! I can help with tax preparation, bookkeeping, consultations, or document questions. What can I assist you with today?' }, position: { x: 250, y: 80 } },
      { id: 'intent', type: 'ai_response', label: 'Detect Intent', config: { prompt: 'Determine the caller\'s intent: tax_preparation, business_consultation, bookkeeping, document_question, deadline_info, billing, or irs_notice. Set caller_intent.', setVariable: 'caller_intent' }, position: { x: 250, y: 160 } },
      { id: 'branch', type: 'condition', label: 'Route', config: { variable: 'caller_intent' }, position: { x: 250, y: 240 } },
      { id: 'tax_prep', type: 'collect_info', label: 'Tax Preparation', config: { fields: ['caller_name', 'phone', 'email', 'filing_type', 'business_type', 'tax_year', 'estimated_income_range', 'preferred_date'], prompt: 'I\'d be happy to get you scheduled for tax prep. Are you filing personal, business, or both? What type of business entity — sole proprietor, LLC, S-Corp, or C-Corp? Do you have all your documents ready, or do you need a checklist?' }, position: { x: 0, y: 340 } },
      { id: 'consult', type: 'collect_info', label: 'Business Consultation', config: { fields: ['caller_name', 'business_name', 'business_type', 'consultation_topic', 'preferred_date', 'preferred_time'], prompt: 'Our consultations cover tax planning, entity structuring, retirement planning, and financial strategy. What specific area are you looking for guidance in? Initial consultations are complimentary for new clients.' }, position: { x: 200, y: 340 } },
      { id: 'docs', type: 'ai_response', label: 'Document Guidance', config: { prompt: 'Provide a document checklist based on their situation. Personal: W-2s, 1099s, mortgage interest (1098), charitable donations, medical expenses, childcare (2441), student loans (1098-E). Business: P&L, balance sheet, 1099-NEC/MISC, payroll reports, asset purchases, mileage log, home office measurements. Mention our secure upload portal.' }, position: { x: 450, y: 340 } },
      { id: 'irs', type: 'escalate', label: 'IRS Notice', config: { message: 'I understand receiving an IRS notice can be stressful. Don\'t worry — let me connect you with one of our tax professionals who can review your notice and advise on next steps. Please have the notice number ready.', priority: 'high' }, position: { x: 650, y: 340 } },
      { id: 'deadline', type: 'ai_response', label: 'Deadline Info', config: { prompt: 'Provide key tax deadlines: April 15 (personal filing), March 15 (S-Corp/Partnership), quarterly estimated payments (4/15, 6/15, 9/15, 1/15), extension deadline Oct 15. Mention: "Filing an extension extends time to file, NOT time to pay. Penalties accrue on unpaid balances."' }, position: { x: 800, y: 340 } },
      { id: 'confirm', type: 'ai_response', label: 'Confirm', config: { prompt: 'Confirm appointment details. Remind them to bring: prior year returns, all income documents, ID, and bank info for direct deposit. Mention our preparation fee range based on complexity.' }, position: { x: 250, y: 480 } },
      { id: 'book', type: 'book_appointment', label: 'Book Appointment', config: { type: '{{caller_intent}} - {{filing_type}}', notes: 'Business type: {{business_type}}. Tax year: {{tax_year}}' }, position: { x: 250, y: 560 } },
      { id: 'contact', type: 'create_contact', label: 'Save Client', config: { source: 'inbound_call', tags: ['accounting', '{{filing_type}}', '{{business_type}}'] }, position: { x: 250, y: 640 } },
      { id: 'sms', type: 'send_sms', label: 'Confirmation', config: { message: 'Hi {{caller_name}}! Your {{caller_intent}} appointment is confirmed for {{preferred_date}}. Please bring: prior year returns, W-2s/1099s, receipts, and photo ID. Upload docs early at our secure portal. See you then!' }, position: { x: 250, y: 720 } },
      { id: 'end', type: 'end_call', label: 'Goodbye', config: { message: 'Thank you for calling! We\'ll make sure you keep more of what you earn. See you at your appointment!' }, position: { x: 250, y: 800 } },
    ],
    edges: [
      { id: 'e1', source: 't', target: 'greet' }, { id: 'e2', source: 'greet', target: 'intent' },
      { id: 'e3', source: 'intent', target: 'branch' },
      { id: 'e4', source: 'branch', target: 'tax_prep', condition: 'caller_intent = tax_preparation', label: 'Tax Prep' },
      { id: 'e5', source: 'branch', target: 'consult', condition: 'caller_intent = business_consultation', label: 'Consult' },
      { id: 'e6', source: 'branch', target: 'docs', condition: 'caller_intent = document_question', label: 'Documents' },
      { id: 'e7', source: 'branch', target: 'irs', condition: 'caller_intent = irs_notice', label: 'IRS Notice' },
      { id: 'e8', source: 'branch', target: 'deadline', condition: 'caller_intent = deadline_info', label: 'Deadlines' },
      { id: 'e9', source: 'branch', target: 'tax_prep', label: 'Default' },
      { id: 'e10', source: 'tax_prep', target: 'confirm' }, { id: 'e11', source: 'consult', target: 'confirm' },
      { id: 'e12', source: 'confirm', target: 'book' }, { id: 'e13', source: 'book', target: 'contact' },
      { id: 'e14', source: 'contact', target: 'sms' }, { id: 'e15', source: 'sms', target: 'end' },
      { id: 'e16', source: 'docs', target: 'end' }, { id: 'e17', source: 'deadline', target: 'end' },
      { id: 'e18', source: 'irs', target: 'end' },
    ],
  },

  // ─── Salon & Spa ────────────────────────────────────────────────────────────
  {
    name: 'Salon & Spa Receptionist',
    description: 'Appointment booking, service recommendations, stylist matching, product inquiries, and gift certificates',
    trigger: 'inbound_call',
    industry: 'salon',
    nodes: [
      { id: 't', type: 'trigger', label: 'Inbound Call', config: { trigger: 'inbound_call' }, position: { x: 250, y: 0 } },
      { id: 'greet', type: 'play_message', label: 'Welcome', config: { message: 'Welcome and thank you for calling! Would you like to book an appointment, learn about our services, request a specific stylist, or purchase a gift certificate?' }, position: { x: 250, y: 80 } },
      { id: 'lookup', type: 'lookup_contact', label: 'Client Lookup', config: { lookupBy: 'phone' }, position: { x: 250, y: 160 } },
      { id: 'intent', type: 'ai_response', label: 'Detect Intent', config: { prompt: 'Determine the caller\'s intent: book_appointment, service_info, stylist_request, gift_certificate, reschedule, products, or bridal_party. Set caller_intent.', setVariable: 'caller_intent' }, position: { x: 250, y: 240 } },
      { id: 'branch', type: 'condition', label: 'Route', config: { variable: 'caller_intent' }, position: { x: 250, y: 320 } },
      { id: 'book', type: 'collect_info', label: 'Book Appointment', config: { fields: ['client_name', 'phone', 'service_type', 'stylist_preference', 'preferred_date', 'preferred_time'], prompt: 'I\'d love to get you booked! What service are you looking for — haircut, color, highlights, blowout, facial, massage, mani/pedi, or a combination? Do you have a preferred stylist? When works best for you?' }, position: { x: 0, y: 420 } },
      { id: 'services', type: 'ai_response', label: 'Service Menu', config: { prompt: 'Describe our services with approximate pricing and duration. Hair: cuts ($45-75, 45min), color ($85-150, 2hr), highlights ($120-200, 2.5hr), blowout ($35-55, 30min), treatments ($30-60). Spa: facial ($75-150, 60min), massage ($80-140, 60-90min), mani ($30), pedi ($45), combo ($65). Mention current promotions and package deals.' }, position: { x: 200, y: 420 } },
      { id: 'stylist', type: 'ai_response', label: 'Stylist Match', config: { prompt: 'Help match the caller with a stylist. Ask about: hair type, desired look, any inspiration photos, budget range. Recommend stylists based on their specialties — balayage specialist, curly hair expert, color correction, bridal styling, etc. Mention stylist availability.' }, position: { x: 400, y: 420 } },
      { id: 'gift', type: 'collect_info', label: 'Gift Certificate', config: { fields: ['buyer_name', 'recipient_name', 'amount', 'delivery_method', 'occasion'], prompt: 'Gift certificates are perfect! We offer custom amounts or specific service packages. Would you like a dollar amount or a specific service — like a spa day package or full makeover? Physical card or digital delivery?' }, position: { x: 600, y: 420 } },
      { id: 'bridal', type: 'collect_info', label: 'Bridal Party', config: { fields: ['bride_name', 'wedding_date', 'party_size', 'services_needed', 'trial_date'], prompt: 'Congratulations! We love doing bridal parties. How many in your bridal party? We offer hair, makeup, and spa packages. We always recommend a trial run 2-4 weeks before the wedding. What\'s your wedding date?' }, position: { x: 750, y: 420 } },
      { id: 'confirm', type: 'ai_response', label: 'Confirm', config: { prompt: 'Confirm all details. Mention: arrive 10 minutes early, cancellation policy (24hr notice), parking information. For color services, remind about patch test if first-time client. For spa, mention what to wear/bring.' }, position: { x: 250, y: 560 } },
      { id: 'book_apt', type: 'book_appointment', label: 'Book', config: { type: '{{service_type}}', notes: 'Stylist: {{stylist_preference}}' }, position: { x: 250, y: 640 } },
      { id: 'contact', type: 'create_contact', label: 'Save Client', config: { source: 'inbound_call', tags: ['salon', '{{service_type}}'] }, position: { x: 250, y: 720 } },
      { id: 'sms', type: 'send_sms', label: 'Confirmation', config: { message: 'Hi {{client_name}}! Your {{service_type}} with {{stylist_preference}} is confirmed for {{preferred_date}} at {{preferred_time}}. Please arrive 10 min early. 24hr cancellation policy applies. Can\'t wait to pamper you!' }, position: { x: 250, y: 800 } },
      { id: 'end', type: 'end_call', label: 'Goodbye', config: { message: 'Thank you for calling! We can\'t wait to make you feel amazing. See you soon!' }, position: { x: 250, y: 880 } },
    ],
    edges: [
      { id: 'e1', source: 't', target: 'greet' }, { id: 'e2', source: 'greet', target: 'lookup' },
      { id: 'e3', source: 'lookup', target: 'intent' }, { id: 'e4', source: 'intent', target: 'branch' },
      { id: 'e5', source: 'branch', target: 'book', condition: 'caller_intent = book_appointment', label: 'Book' },
      { id: 'e6', source: 'branch', target: 'services', condition: 'caller_intent = service_info', label: 'Services' },
      { id: 'e7', source: 'branch', target: 'stylist', condition: 'caller_intent = stylist_request', label: 'Stylist' },
      { id: 'e8', source: 'branch', target: 'gift', condition: 'caller_intent = gift_certificate', label: 'Gift Card' },
      { id: 'e9', source: 'branch', target: 'bridal', condition: 'caller_intent = bridal_party', label: 'Bridal' },
      { id: 'e10', source: 'branch', target: 'book', label: 'Default' },
      { id: 'e11', source: 'book', target: 'confirm' }, { id: 'e12', source: 'gift', target: 'confirm' },
      { id: 'e13', source: 'bridal', target: 'confirm' }, { id: 'e14', source: 'stylist', target: 'book' },
      { id: 'e15', source: 'confirm', target: 'book_apt' }, { id: 'e16', source: 'book_apt', target: 'contact' },
      { id: 'e17', source: 'contact', target: 'sms' }, { id: 'e18', source: 'sms', target: 'end' },
      { id: 'e19', source: 'services', target: 'end' },
    ],
  },

  // ─── Auto Repair ────────────────────────────────────────────────────────────
  {
    name: 'Auto Repair Advisor',
    description: 'Service scheduling, diagnostic estimates, recall checks, repair status updates, and towing coordination',
    trigger: 'inbound_call',
    industry: 'auto repair',
    nodes: [
      { id: 't', type: 'trigger', label: 'Inbound Call', config: { trigger: 'inbound_call' }, position: { x: 250, y: 0 } },
      { id: 'greet', type: 'play_message', label: 'Welcome', config: { message: 'Thanks for calling the shop! Do you need to schedule service, get an estimate, check on a vehicle, or need a tow?' }, position: { x: 250, y: 80 } },
      { id: 'intent', type: 'ai_response', label: 'Detect Intent', config: { prompt: 'Determine the caller\'s intent: schedule_service, diagnostic_estimate, status_check, recall_inquiry, towing, warranty, or tire_service. Set caller_intent.', setVariable: 'caller_intent' }, position: { x: 250, y: 160 } },
      { id: 'branch', type: 'condition', label: 'Route', config: { variable: 'caller_intent' }, position: { x: 250, y: 240 } },
      { id: 'service', type: 'collect_info', label: 'Schedule Service', config: { fields: ['caller_name', 'phone', 'vehicle_year', 'vehicle_make', 'vehicle_model', 'mileage', 'service_needed', 'symptoms', 'preferred_date', 'preferred_time'], prompt: 'I\'d be happy to schedule that! What\'s the year, make, and model? What mileage are you at? What service do you need — oil change, brakes, tires, engine issue, or something else? Can you describe any symptoms?' }, position: { x: 0, y: 340 } },
      { id: 'estimate', type: 'collect_info', label: 'Get Estimate', config: { fields: ['caller_name', 'vehicle_year', 'vehicle_make', 'vehicle_model', 'issue_description'], prompt: 'I can get you a ballpark estimate. What\'s your vehicle, and what work do you need done? For accurate quotes, we recommend a free diagnostic inspection. Common estimates: oil change ($35-75), brake pads ($150-300/axle), tire rotation ($25-50).' }, position: { x: 200, y: 340 } },
      { id: 'status', type: 'collect_info', label: 'Check Status', config: { fields: ['caller_name', 'vehicle_description', 'drop_off_date'], prompt: 'Let me check on your vehicle. What\'s your name and what vehicle did you drop off? I\'ll get an update from the tech.' }, position: { x: 400, y: 340 } },
      { id: 'recall', type: 'ai_response', label: 'Recall Check', config: { prompt: 'Help check for recalls. Ask for VIN number or year/make/model. Explain: recall repairs are always free, performed by certified technicians, and use OEM parts. Offer to schedule the recall service and mention typical completion time.' }, position: { x: 600, y: 340 } },
      { id: 'towing', type: 'escalate', label: 'Towing', config: { message: 'I\'ll get a tow truck dispatched right away. What\'s your current location? Are you in a safe spot? Our tow service typically arrives within 30-45 minutes. The tow is free if we do the repair.', priority: 'high' }, position: { x: 750, y: 340 } },
      { id: 'confirm', type: 'ai_response', label: 'Confirm', config: { prompt: 'Confirm appointment details. Mention: drop-off time, estimated completion time, free shuttle service within 5 miles, loaner vehicles available for major repairs. Remind about our price-match guarantee.' }, position: { x: 250, y: 480 } },
      { id: 'book', type: 'book_appointment', label: 'Book Service', config: { type: '{{service_needed}} - {{vehicle_year}} {{vehicle_make}} {{vehicle_model}}', notes: 'Mileage: {{mileage}}. Symptoms: {{symptoms}}' }, position: { x: 250, y: 560 } },
      { id: 'contact', type: 'create_contact', label: 'Save Customer', config: { source: 'inbound_call', tags: ['auto-repair', '{{vehicle_make}}'] }, position: { x: 250, y: 640 } },
      { id: 'sms', type: 'send_sms', label: 'Confirmation', config: { message: 'Hi {{caller_name}}! Your {{service_needed}} appointment for your {{vehicle_year}} {{vehicle_make}} {{vehicle_model}} is set for {{preferred_date}} at {{preferred_time}}. Drop-off starts at 7:30 AM. We\'ll text you updates throughout the day!' }, position: { x: 250, y: 720 } },
      { id: 'end', type: 'end_call', label: 'Goodbye', config: { message: 'Thanks for calling! We\'ll take great care of your vehicle. See you at the shop!' }, position: { x: 250, y: 800 } },
    ],
    edges: [
      { id: 'e1', source: 't', target: 'greet' }, { id: 'e2', source: 'greet', target: 'intent' },
      { id: 'e3', source: 'intent', target: 'branch' },
      { id: 'e4', source: 'branch', target: 'service', condition: 'caller_intent = schedule_service', label: 'Service' },
      { id: 'e5', source: 'branch', target: 'estimate', condition: 'caller_intent = diagnostic_estimate', label: 'Estimate' },
      { id: 'e6', source: 'branch', target: 'status', condition: 'caller_intent = status_check', label: 'Status' },
      { id: 'e7', source: 'branch', target: 'recall', condition: 'caller_intent = recall_inquiry', label: 'Recall' },
      { id: 'e8', source: 'branch', target: 'towing', condition: 'caller_intent = towing', label: 'Tow' },
      { id: 'e9', source: 'branch', target: 'service', label: 'Default' },
      { id: 'e10', source: 'service', target: 'confirm' }, { id: 'e11', source: 'estimate', target: 'confirm' },
      { id: 'e12', source: 'confirm', target: 'book' }, { id: 'e13', source: 'book', target: 'contact' },
      { id: 'e14', source: 'contact', target: 'sms' }, { id: 'e15', source: 'sms', target: 'end' },
      { id: 'e16', source: 'status', target: 'end' }, { id: 'e17', source: 'recall', target: 'end' },
      { id: 'e18', source: 'towing', target: 'end' },
    ],
  },
]
